name: Verify OpenRouter Key

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure OPENROUTER_API_KEY is set
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          if [ -z "${OPENROUTER_API_KEY:-}" ]; then
            echo "ERROR: OPENROUTER_API_KEY secret is not configured for this repository. Please add it under Settings → Secrets."
            exit 1
          fi

      - name: Install deps
        run: npm ci

      - name: Verify OPENROUTER_API_KEY
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}
        run: |
          node bin/verify-openrouter.js
